<?php

namespace Database\Seeders;

use App\Models\Bootcamp;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BootcampSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bootcamps = [
            [
                'slug' => 'web-development',
                'title' => 'بوتکمپ توسعه وب',
                'thumbnail' => 'web-dev.jpg',
                'cover' => 'web-dev-cover.jpg',
                'overview' => 'آموزش کامل توسعه وب از صفر تا صد با جدیدترین تکنولوژی‌ها.',
                'curriculum' => json_encode(['HTML', 'CSS', 'JavaScript', 'React', 'Node.js']),
                'level' => 'مبتدی تا پیشرفته',
                'duration' => '۶ ماه',
                'lessons' => 45,
                'quizzes' => 10,
                'certification' => true,
                'intro_video' => 'web-dev-intro.mp4',
                'price' => 5000000,
            ],
            [
                'slug' => 'data-science',
                'title' => 'بوتکمپ علم داده',
                'thumbnail' => 'data-science.jpg',
                'cover' => 'data-science-cover.jpg',
                'overview' => 'یادگیری علم داده با پایتون و یادگیری ماشین.',
                'curriculum' => json_encode(['Python', 'Pandas', 'Machine Learning', 'Deep Learning']),
                'level' => 'متوسط تا پیشرفته',
                'duration' => '۴ ماه',
                'lessons' => 30,
                'quizzes' => 8,
                'certification' => true,
                'intro_video' => 'data-science-intro.mp4',
                'price' => 6000000,
            ],
            [
                'slug' => 'cyber-security',
                'title' => 'بوتکمپ امنیت سایبری',
                'thumbnail' => 'cyber-security.jpg',
                'cover' => 'cyber-security-cover.jpg',
                'overview' => 'مهارت‌های لازم برای امنیت سایبری و هک اخلاقی.',
                'curriculum' => json_encode(['Networking', 'Ethical Hacking', 'Penetration Testing']),
                'level' => 'متوسط تا پیشرفته',
                'duration' => '۵ ماه',
                'lessons' => 35,
                'quizzes' => 9,
                'certification' => true,
                'intro_video' => 'cyber-security-intro.mp4',
                'price' => 7000000,
            ],
            [
                'slug' => 'mobile-development',
                'title' => 'بوتکمپ توسعه اپلیکیشن موبایل',
                'thumbnail' => 'mobile-dev.jpg',
                'cover' => 'mobile-dev-cover.jpg',
                'overview' => 'ساخت اپلیکیشن‌های موبایل با Flutter و React Native.',
                'curriculum' => json_encode(['Flutter', 'Dart', 'React Native', 'Swift']),
                'level' => 'مبتدی تا پیشرفته',
                'duration' => '۵ ماه',
                'lessons' => 40,
                'quizzes' => 7,
                'certification' => true,
                'intro_video' => 'mobile-dev-intro.mp4',
                'price' => 5500000,
            ],
            [
                'slug' => 'ai-ml',
                'title' => 'بوتکمپ هوش مصنوعی و یادگیری ماشین',
                'thumbnail' => 'ai-ml.jpg',
                'cover' => 'ai-ml-cover.jpg',
                'overview' => 'هوش مصنوعی و یادگیری ماشین با تمرین‌های عملی.',
                'curriculum' => json_encode(['Python', 'TensorFlow', 'Neural Networks']),
                'level' => 'پیشرفته',
                'duration' => '۶ ماه',
                'lessons' => 50,
                'quizzes' => 12,
                'certification' => true,
                'intro_video' => 'ai-ml-intro.mp4',
                'price' => 8000000,
            ],
            [
                'slug' => 'game-development',
                'title' => 'بوتکمپ توسعه بازی',
                'thumbnail' => 'game-dev.jpg',
                'cover' => 'game-dev-cover.jpg',
                'overview' => 'یادگیری توسعه بازی‌های دوبعدی و سه‌بعدی.',
                'curriculum' => json_encode(['Unity', 'C#', 'Game Design']),
                'level' => 'متوسط',
                'duration' => '۴ ماه',
                'lessons' => 30,
                'quizzes' => 6,
                'certification' => true,
                'intro_video' => 'game-dev-intro.mp4',
                'price' => 6500000,
            ],
            [
                'slug' => 'devops',
                'title' => 'بوتکمپ DevOps',
                'thumbnail' => 'devops.jpg',
                'cover' => 'devops-cover.jpg',
                'overview' => 'مبانی DevOps، CI/CD و Docker/Kubernetes.',
                'curriculum' => json_encode(['Linux', 'Docker', 'Kubernetes', 'CI/CD']),
                'level' => 'پیشرفته',
                'duration' => '۴ ماه',
                'lessons' => 35,
                'quizzes' => 9,
                'certification' => true,
                'intro_video' => 'devops-intro.mp4',
                'price' => 7000000,
            ],
            [
                'slug' => 'blockchain',
                'title' => 'بوتکمپ بلاکچین',
                'thumbnail' => 'blockchain.jpg',
                'cover' => 'blockchain-cover.jpg',
                'overview' => 'مفاهیم بلاکچین، قراردادهای هوشمند و Web3.',
                'curriculum' => json_encode(['Ethereum', 'Solidity', 'Smart Contracts']),
                'level' => 'پیشرفته',
                'duration' => '۵ ماه',
                'lessons' => 40,
                'quizzes' => 8,
                'certification' => true,
                'intro_video' => 'blockchain-intro.mp4',
                'price' => 7500000,
            ],
            [
                'slug' => 'digital-marketing',
                'title' => 'بوتکمپ دیجیتال مارکتینگ',
                'thumbnail' => 'digital-marketing.jpg',
                'cover' => 'digital-marketing-cover.jpg',
                'overview' => 'یادگیری تبلیغات دیجیتال، SEO و بازاریابی محتوا.',
                'curriculum' => json_encode(['SEO', 'Google Ads', 'Social Media']),
                'level' => 'مبتدی تا متوسط',
                'duration' => '۳ ماه',
                'lessons' => 25,
                'quizzes' => 5,
                'certification' => true,
                'intro_video' => 'digital-marketing-intro.mp4',
                'price' => 4000000,
            ],
            [
                'slug' => 'ux-ui',
                'title' => 'بوتکمپ طراحی UX/UI',
                'thumbnail' => 'ux-ui.jpg',
                'cover' => 'ux-ui-cover.jpg',
                'overview' => 'اصول طراحی تجربه و رابط کاربری با Figma و Adobe XD.',
                'curriculum' => json_encode(['Figma', 'Adobe XD', 'User Research']),
                'level' => 'مبتدی تا متوسط',
                'duration' => '۴ ماه',
                'lessons' => 30,
                'quizzes' => 6,
                'certification' => true,
                'intro_video' => 'ux-ui-intro.mp4',
                'price' => 5000000,
            ],
            [
                'slug' => 'cloud-computing',
                'title' => 'بوتکمپ رایانش ابری',
                'thumbnail' => 'cloud.jpg',
                'cover' => 'cloud-cover.jpg',
                'overview' => 'آموزش AWS، Azure و Google Cloud.',
                'curriculum' => json_encode(['AWS', 'Azure', 'Google Cloud']),
                'level' => 'پیشرفته',
                'duration' => '۶ ماه',
                'lessons' => 40,
                'quizzes' => 10,
                'certification' => true,
                'intro_video' => 'cloud-intro.mp4',
                'price' => 8500000,
            ],
        ];

        foreach ($bootcamps as $bootcamp) {
            Bootcamp::create($bootcamp);
        }

    }
}
